# Checkov configuration to suppress false positives
# See https://www.checkov.io/2.Basics/CLI%20Command%20Reference.html

# Suppress checks globally
skip-check:
  # CKV_GIT_4: GitHub Actions secrets encrypted check
  # False positive: GitHub API automatically encrypts secrets server-side
  # The terraform provider requires plaintext_value, but GitHub encrypts on upload
  - CKV_GIT_4
