version: '3.8'

services:
  jaeger:
    image: jaegertracing/all-in-one:1.51
    container_name: jaeger
    environment:
      # Enable OTLP collector for OpenTelemetry compatibility
      - COLLECTOR_OTLP_ENABLED=true
      # Configure storage backend
      - SPAN_STORAGE_TYPE=memory
      # Memory storage settings (for development)
      - MEMORY_MAX_TRACES=100000
      # Sampling configuration
      - SAMPLING_STRATEGIES_FILE=/etc/jaeger/sampling_strategies.json
    ports:
      # Jaeger UI
      - "16686:16686"
      # OTLP HTTP collector (OpenTelemetry)
      - "4318:4318"
      # OTLP gRPC collector
      - "4317:4317"
      # Jaeger Thrift HTTP collector (legacy)
      - "14268:14268"
      # Jaeger agent (UDP)
      - "6831:6831/udp"
      # Jaeger agent (compact)
      - "6832:6832/udp"
      # Jaeger collector HTTP
      - "14250:14250"
      # Health check
      - "14269:14269"
    volumes:
      - ./jaeger-sampling.json:/etc/jaeger/sampling_strategies.json:ro
    networks:
      - observability
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:14269/"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s
    restart: unless-stopped

  # Optional: Elasticsearch for production storage
  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
  #   container_name: elasticsearch
  #   environment:
  #     - discovery.type=single-node
  #     - xpack.security.enabled=false
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #   ports:
  #     - "9200:9200"
  #   volumes:
  #     - elasticsearch-data:/usr/share/elasticsearch/data
  #   networks:
  #     - observability
  #   healthcheck:
  #     test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 5

  # jaeger-with-elasticsearch:
  #   image: jaegertracing/all-in-one:1.51
  #   container_name: jaeger-production
  #   environment:
  #     - COLLECTOR_OTLP_ENABLED=true
  #     - SPAN_STORAGE_TYPE=elasticsearch
  #     - ES_SERVER_URLS=http://elasticsearch:9200
  #   depends_on:
  #     - elasticsearch
  #   ports:
  #     - "16686:16686"
  #     - "4318:4318"
  #     - "14268:14268"
  #   networks:
  #     - observability

networks:
  observability:
    driver: bridge

# volumes:
#   elasticsearch-data:
#     driver: local
