AWSTemplateFormatVersion: '2010-09-09'
Description: 'Minimal test template for tomriddelsdell.com deployment'

Parameters:
  ProjectName:
    Type: String
    Default: tomriddelsdell-com
    Description: Project name for resource naming
  
  Environment:
    Type: String
    Default: production
    Description: Environment name

Resources:
  # Simple S3 bucket for testing
  TestBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${ProjectName}-${Environment}-test-bucket'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

Outputs:
  BucketName:
    Description: Test bucket name
    Value: !Ref TestBucket
    Export:
      Name: !Sub '${ProjectName}-${Environment}-test-bucket'
